"""init

Revision ID: 6844d3b129a1
Revises: 
Create Date: 2025-09-06 01:40:49.563514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6844d3b129a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo_tags', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_articulo_tag', ['articulo_id', 'tag_id'])

    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=160),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('img_fuente',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('autor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('tag',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_articulos_fecha_date'))
        batch_op.create_index('ix_articulos_slug', ['slug'], unique=True)

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_index('ix_articulos_slug')
        batch_op.create_index(batch_op.f('idx_articulos_fecha_date'), ['fecha'], unique=False)
        batch_op.alter_column('tag',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('autor',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('img_fuente',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=160),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('articulo_tags', schema=None) as batch_op:
        batch_op.drop_constraint('uq_articulo_tag', type_='unique')

    # ### end Alembic commands ###
