name: Refresh Mercados (12h)

on:
  schedule:
    # Corre a :00 cada 12 horas (UTC): 00:00 y 12:00
    - cron: "0 */12 * * *"
  # Permite ejecutarlo manualmente cuando quieras
  workflow_dispatch:

jobs:
  refresh-mercados:
    runs-on: ubuntu-latest
    concurrency:
      group: refresh-mercados
      cancel-in-progress: false
    steps:
      - name: Call Render App (wake up)
        run: |
          curl -sS -m 20 "${{ secrets.SITE_URL }}/" || true

      - name: Call Refresh Mercados Endpoint
        run: |
          curl -i -X POST \
            "${{ secrets.SITE_URL }}/tasks/refresh-mercados" \
            -H "X-Refresh-Token: ${{ secrets.CANAL_KEY }}" \
            --retry 6 --retry-all-errors --retry-delay 10 \
            --connect-timeout 10 --max-time 60
